# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
        environment:
          IS_CI: "true"

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
    
      - run: node mockFirebaseSettingsInCI.js

      - run: npm install
      - run: npm install http-server


      - run: ./node_modules/.bin/ng build --prod
      - run:
          background: true
          command: ./node_modules/.bin/http-server ./dist

      # ngrok for making server publicly accessible
      - run: wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
      - run: unzip ngrok-stable-linux-amd64.zip
      - run: chmod +x ngrok
      - run: ./ngrok authtoken ${NGROK_TOKEN}
      - run:
          background: true
          # stdout bc this: https://github.com/inconshreveable/ngrok/issues/57
          command: ./ngrok http 8080 -log=stdout


      - run: npm install debugbear
      - run: ./node_modules/.bin/debugbear --pageId=721 --ngrokWebPort=4040 --waitForResult --baseBranch=master

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      